In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
import os
current_path = os.getcwd()

folder_path = os.path.dirname(os.path.dirname(current_path))
print(folder_path)


df = pd.read_json(f"{folder_path}/DataScraping/rever.com_spider/data/nhadat.json")
df

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4836 entries, 0 to 4835
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             4836 non-null   object
 1   title           4835 non-null   object
 2   price           4836 non-null   object
 3   price_per_area  4836 non-null   object
 4   land_area       4836 non-null   object
 5   floor_area      4836 non-null   object
 6   type            4836 non-null   object
 7   bedrooms        4836 non-null   object
 8   bathrooms       4836 non-null   int64
 9   address         4836 non-null   object
 10  direction       4836 non-null   object
 11  floor           4836 non-null   object
 12  law_doc         4836 non-null   object
 13  furniture       4836 non-null   object
 14  entrance        4836 non-null   object
 15  project         4836 non-null   object
 16  post_date       4836 non-null   object
 17  id              4836 non-null   object
 18  utilities       236 non-null    object
dtypes: int64(1), object(18)
memory usage: 718.0+ KB

In [28]:
rows_with_nan_in_title = df[df['title'].isna()]

# In ra các hàng có giá trị NaN trong cột 'title'
print("Các hàng có giá trị NaN trong cột 'title':")
print(rows_with_nan_in_title)

df['title'] = df['title'].fillna('KXĐ')

Các hàng có giá trị NaN trong cột 'title':
                                                   url title   price  \
420  https://rever.vn/mua/nha-pho-duong-nhi-binh-21...   NaN  3.5 tỷ

     price_per_area land_area floor_area     type bedrooms  bathrooms  \
420  53.03 triệu/m²   66.3 m²    66.3 m²  Nhà phố        1          1

                            address direction floor  law_doc  \
420  Nhị Bình 21, Nhị Bình, Hóc Môn   Tây Bắc     1  Sổ hồng

             furniture entrance project   post_date         id utilities
420  Không có nội thất      KXĐ     KXĐ  28/02/2023  THM142026   Nhà kho

In [29]:
duplicate_rows = df[df.duplicated(subset=['title', 'floor_area'], keep='first')]

print("\nCác hàng trùng lặp sau lần xuất hiện đầu tiên:")
print(duplicate_rows.index)

Các hàng trùng lặp sau lần xuất hiện đầu tiên:
Index([399, 1311, 2388, 2553, 4141], dtype='int64')

In [30]:
duplicate_rows

,url,title,price,price_per_area,land_area,floor_area,type,bedrooms,bathrooms,address,direction,floor,law_doc,furniture,entrance,project,post_date,id,utilities
399,https://rever.vn/mua/mua-ban-nha-biet-thu-lien...,"Mua bán nhà biệt thự, liền kề tại Vinhomes Gra...",13 tỷ,154.76 triệu/m²,84 m²,245 m²,Nhà phố,5,4,"Nguyễn Xiển, Long Thạnh Mỹ, Quận 9",Tây Bắc,5,HĐ mua bán,Không có nội thất,7m,Vinhomes Grand Park,14/12/2023,T09159864,"Ban công, Chỗ đậu xe hơi"
1311,https://rever.vn/mua/nha-pho-thiet-ke-1-tret-1...,"Nhà phố thiết kế 1 trệt, 1 lầu diện tích 45m2,...",5.5 tỷ,122.22 triệu/m²,45 m²,90 m²,Nhà phố,3,2,"Trần Văn Quang, Phường 10, Tân Bình",KXĐ,2,Sổ hồng,Không có nội thất,KXĐ,KXĐ,07/12/2022,TTB108542,NaN
2388,https://rever.vn/mua/nha-pho-duong-thoi-an-20-...,Nhà phố Đường Thới An 20 4 tầng diện tích 52.4...,5.05 tỷ,97.12 triệu/m²,52.4 m²,166.9 m²,Nhà phố,4,4,"Thới An 20, Thới An, Quận 12",Bắc,4,Sổ hồng,Đầy đủ nội thất,KXĐ,KXĐ,04/10/2022,T12116928,NaN
2553,https://rever.vn/mua/nha-pho-duong-nguyen-than...,Nhà phố Đường Nguyễn Thần Hiến 2 tầng diện tíc...,7.2 tỷ,100 triệu/m²,72.3 m²,149.1 m²,Nhà phố,3,3,"Nguyễn Thần Hiến, Phường 18, Quận 4",Tây Nam,2,Sổ hồng,Đầy đủ nội thất,2m,KXĐ,11/10/2022,T04117840,NaN
4141,https://rever.vn/mua/nha-pho-thiet-ke-1-tret-1...,"Nhà phố thiết kế 1 trệt, 1 lầu diện tích đất 6...",8.7 tỷ,145 triệu/m²,60.2 m²,123.3 m²,Nhà phố,2,2,"Bạch Đằng, Phường 2, Tân Bình",KXĐ,2,Sổ hồng,Nội thất cơ bản,KXĐ,KXĐ,27/07/2022,TTB110778,NaN

In [31]:
df = df.drop_duplicates(subset=['title', 'floor_area'], keep='first')

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4831 entries, 0 to 4835
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             4831 non-null   object
 1   title           4831 non-null   object
 2   price           4831 non-null   object
 3   price_per_area  4831 non-null   object
 4   land_area       4831 non-null   object
 5   floor_area      4831 non-null   object
 6   type            4831 non-null   object
 7   bedrooms        4831 non-null   object
 8   bathrooms       4831 non-null   int64
 9   address         4831 non-null   object
 10  direction       4831 non-null   object
 11  floor           4831 non-null   object
 12  law_doc         4831 non-null   object
 13  furniture       4831 non-null   object
 14  entrance        4831 non-null   object
 15  project         4831 non-null   object
 16  post_date       4831 non-null   object
 17  id              4831 non-null   object
 18  utilities       235 non-null    object
dtypes: int64(1), object(18)
memory usage: 754.8+ KB

In [32]:
df.head()

,url,title,price,price_per_area,land_area,floor_area,type,bedrooms,bathrooms,address,direction,floor,law_doc,furniture,entrance,project,post_date,id,utilities
0,https://rever.vn/mua/nha-pho-duong-bui-quang-l...,"Nhà phố đường Bùi Quang Là 4 tầng, diện tích 5...",6.9 tỷ,130.19 triệu/m²,53.6 m²,1852 m²,Nhà phố,3,3,"Bùi Quang Là, Phường 12, Gò Vấp",Tây Nam,4,Sổ hồng,Nội thất cơ bản,3.5m,KXĐ,07/12/2023,TGV191915,NaN
1,https://rever.vn/mua/nha-pho-duong-le-dinh-qua...,"Nhà phố đường Lê Đình Quản 3 tầng, diện tích 9...",9.1 tỷ,94.79 triệu/m²,96 m²,212.6 m²,Nhà phố,3,4,"Lê Đình Quản, Cát Lái, Quận 2",Đông Nam,3,Sổ hồng,Đầy đủ nội thất,4m,KXĐ,11/12/2023,T02192348,NaN
2,https://rever.vn/mua/nha-pho-duong-phan-van-tr...,Nhà phố Đường Phan Văn Trị 4 tầng diện tích 43...,6.8 tỷ,158.14 triệu/m²,43.8 m²,135.9 m²,Nhà phố,5,5,"Phan Văn Trị, Phường 11, Bình Thạnh",Đông Nam,4,Sổ hồng,Không có nội thất,KXĐ,KXĐ,20/09/2023,TBT118180,NaN
3,https://rever.vn/mua/nha-pho-duong-lien-khu-2-...,Nhà phố Đường Liên khu 2-5 1 tầng diện tích 35...,3.4 tỷ,97.14 triệu/m²,35.7 m²,68.5 m²,Nhà phố,2,1,"Liên khu 2-5, Hiệp Thành, Quận 12",Tây Nam,1,Sổ hồng,Nội thất cơ bản,3m,KXĐ,12/09/2023,T12187337,NaN
4,https://rever.vn/mua/nha-pho-duong-binh-tri-do...,Nhà phố Đường Bình Trị Đông 3 tầng diện tích 1...,5.7 tỷ,34.34 triệu/m²,166 m²,166 m²,Nhà phố,4,3,"Bình Trị Đông, Bình Trị Đông, Bình Tân",Đông,3,Sổ hồng,Đầy đủ nội thất,4m,KXĐ,29/08/2023,TTA187189,NaN

In [33]:
df = df.drop(['title','url'],axis=1)

In [34]:
law_doc_values = df['law_doc'].unique()
furniture_values = df['furniture'].unique()
type_values = df['type'].unique()

In [35]:
furniture_values

array(['Nội thất cơ bản', 'Đầy đủ nội thất', 'Không có nội thất', 'KXĐ'],
      dtype=object)

In [36]:
law_doc_mapping = { 'Sổ hồng': 0, 'HĐ mua bán': 1, 'Sổ đỏ': 2, 'Giấy tay': 3, 'KXĐ': -1}
furniture_mapping = {'Không có nội thất': 0, 'Đầy đủ nội thất' : 1, 'Nội thất cơ bản': 2, 'KXĐ': -1}

df['law_doc'] = df['law_doc'].map(law_doc_mapping)
df['furniture'] = df['furniture'].map(furniture_mapping)


df.head()

,price,price_per_area,land_area,floor_area,type,bedrooms,bathrooms,address,direction,floor,law_doc,furniture,entrance,project,post_date,id,utilities
0,6.9 tỷ,130.19 triệu/m²,53.6 m²,1852 m²,Nhà phố,3,3,"Bùi Quang Là, Phường 12, Gò Vấp",Tây Nam,4,0,2,3.5m,KXĐ,07/12/2023,TGV191915,NaN
1,9.1 tỷ,94.79 triệu/m²,96 m²,212.6 m²,Nhà phố,3,4,"Lê Đình Quản, Cát Lái, Quận 2",Đông Nam,3,0,1,4m,KXĐ,11/12/2023,T02192348,NaN
2,6.8 tỷ,158.14 triệu/m²,43.8 m²,135.9 m²,Nhà phố,5,5,"Phan Văn Trị, Phường 11, Bình Thạnh",Đông Nam,4,0,0,KXĐ,KXĐ,20/09/2023,TBT118180,NaN
3,3.4 tỷ,97.14 triệu/m²,35.7 m²,68.5 m²,Nhà phố,2,1,"Liên khu 2-5, Hiệp Thành, Quận 12",Tây Nam,1,0,2,3m,KXĐ,12/09/2023,T12187337,NaN
4,5.7 tỷ,34.34 triệu/m²,166 m²,166 m²,Nhà phố,4,3,"Bình Trị Đông, Bình Trị Đông, Bình Tân",Đông,3,0,1,4m,KXĐ,29/08/2023,TTA187189,NaN

In [37]:
def convert_price(price):
    price = price.strip()  # Loại bỏ khoảng trắng dư thừa
    if 'tỷ' in price:
        return float(price.replace(' tỷ', ''))  # Chuyển đổi "tỷ" thành số và nhân với 1 tỷ
    elif 'triệu' in price:
        return float(price.replace(' triệu', '')) * 0.001  # Chuyển đổi "triệu" thành số và nhân với 1 triệu
    elif ' tr' in price:
        return float(price.replace(' tr', '')) * 0.001
    else:
        return None  # Trường hợp giá trị không hợp lệ
    
def convert_price_per_area(price):
    price = price.strip()  # Loại bỏ khoảng trắng dư thừa nếu có
    if 'triệu/m²' in price:
        return float(price.replace(' triệu/m²', ''))  # Xử lý trường hợp "triệu/m²"
    elif 'nghìn/m²' in price:
        return float(price.replace(' nghìn/m²', '')) * 0.001  # Xử lý trường hợp "nghìn/m²", chuyển sang "triệu/m²"
    else:
        return None  # Trường hợp không hợp lệ hoặc giá trị không chứa "triệu" hoặc "nghìn"

    
df['price'] = df['price'].apply(convert_price)

df['price_per_area'] = df['price_per_area'].apply(convert_price_per_area)

df['land_area'] = df['land_area'].str.replace(' m²', '', regex=False)
df['land_area'] = df['land_area'].str.replace(',', '', regex=False)
df['land_area'] = df['land_area'].astype(float)


df['floor_area'] = df['floor_area'].str.replace(' m²', '', regex=False)
df['floor_area'] = df['floor_area'].str.replace(',', '', regex=False).astype(float)
df['floor_area'] = df['floor_area'].astype(float)



df.head()

,price,price_per_area,land_area,floor_area,type,bedrooms,bathrooms,address,direction,floor,law_doc,furniture,entrance,project,post_date,id,utilities
0,6.9,130.19,53.6,1852.0,Nhà phố,3,3,"Bùi Quang Là, Phường 12, Gò Vấp",Tây Nam,4,0,2,3.5m,KXĐ,07/12/2023,TGV191915,NaN
1,9.1,94.79,96.0,212.6,Nhà phố,3,4,"Lê Đình Quản, Cát Lái, Quận 2",Đông Nam,3,0,1,4m,KXĐ,11/12/2023,T02192348,NaN
2,6.8,158.14,43.8,135.9,Nhà phố,5,5,"Phan Văn Trị, Phường 11, Bình Thạnh",Đông Nam,4,0,0,KXĐ,KXĐ,20/09/2023,TBT118180,NaN
3,3.4,97.14,35.7,68.5,Nhà phố,2,1,"Liên khu 2-5, Hiệp Thành, Quận 12",Tây Nam,1,0,2,3m,KXĐ,12/09/2023,T12187337,NaN
4,5.7,34.34,166.0,166.0,Nhà phố,4,3,"Bình Trị Đông, Bình Trị Đông, Bình Tân",Đông,3,0,1,4m,KXĐ,29/08/2023,TTA187189,NaN

In [38]:
df['utilities_list'] = df['utilities'].fillna('').str.split(', ')

# Áp dụng hàm lambda để tạo dummy columns cho các tiện ích
utilities_dummies = df['utilities_list'].apply(lambda x: pd.Series(1, index=x)).fillna(0)

# Gộp các cột tiện ích vào DataFrame gốc
df = pd.concat([df, utilities_dummies], axis=1)

df.head()

,price,price_per_area,land_area,floor_area,type,bedrooms,bathrooms,address,direction,floor,...,Nuôi thú cưng,Phòng cho giúp việc,Phòng giải trí,Quầy minibar,Tầng hầm,Góc làm việc,Nhà kho,Gym,Hồ bơi riêng,Giếng trời
0,6.9,130.19,53.6,1852.0,Nhà phố,3,3,"Bùi Quang Là, Phường 12, Gò Vấp",Tây Nam,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,9.1,94.79,96.0,212.6,Nhà phố,3,4,"Lê Đình Quản, Cát Lái, Quận 2",Đông Nam,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,6.8,158.14,43.8,135.9,Nhà phố,5,5,"Phan Văn Trị, Phường 11, Bình Thạnh",Đông Nam,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.4,97.14,35.7,68.5,Nhà phố,2,1,"Liên khu 2-5, Hiệp Thành, Quận 12",Tây Nam,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.7,34.34,166.0,166.0,Nhà phố,4,3,"Bình Trị Đông, Bình Trị Đông, Bình Tân",Đông,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
df = df.drop(['utilities','utilities_list', ""], axis = 1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4831 entries, 0 to 4835
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                4831 non-null   float64
 1   price_per_area       4829 non-null   float64
 2   land_area            4831 non-null   float64
 3   floor_area           4831 non-null   float64
 4   type                 4831 non-null   object
 5   bedrooms             4831 non-null   object
 6   bathrooms            4831 non-null   int64
 7   address              4831 non-null   object
 8   direction            4831 non-null   object
 9   floor                4831 non-null   object
 10  law_doc              4831 non-null   int64
 11  furniture            4831 non-null   int64
 12  entrance             4831 non-null   object
 13  project              4831 non-null   object
 14  post_date            4831 non-null   object
 15  id                   4831 non-null   object
 16  Ban công             4831 non-null   float64
 17  Sân vườn             4831 non-null   float64
 18  Chỗ đậu xe hơi       4831 non-null   float64
 19  Nuôi thú cưng        4831 non-null   float64
 20  Phòng cho giúp việc  4831 non-null   float64
 21  Phòng giải trí       4831 non-null   float64
 22  Quầy minibar         4831 non-null   float64
 23  Tầng hầm             4831 non-null   float64
 24  Góc làm việc         4831 non-null   float64
 25  Nhà kho              4831 non-null   float64
 26  Gym                  4831 non-null   float64
 27  Hồ bơi riêng         4831 non-null   float64
 28  Giếng trời           4831 non-null   float64
dtypes: float64(17), int64(3), object(9)
memory usage: 1.1+ MB

In [43]:
nan_rows = df[df.isna().any(axis=1)]
print(nan_rows)

      price  price_per_area  land_area  floor_area     type bedrooms  \
1290   12.0             NaN       12.0       124.0  Nhà phố        4
2900    6.5             NaN        6.7        26.9  Nhà phố        2

      bathrooms                               address direction floor  ...  \
1290          3  Nguyễn Thiện Thuật, Phường 2, Quận 3       KXĐ     4  ...
2900          1         3 Tháng 2, Phường 11, Quận 10       KXĐ     4  ...

      Nuôi thú cưng  Phòng cho giúp việc Phòng giải trí Quầy minibar Tầng hầm  \
1290            0.0                  0.0            0.0          0.0      0.0
2900            0.0                  0.0            0.0          0.0      0.0

     Góc làm việc  Nhà kho  Gym  Hồ bơi riêng  Giếng trời
1290          0.0      0.0  0.0           0.0         0.0
2900          0.0      0.0  0.0           0.0         0.0

[2 rows x 29 columns]

In [45]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4829 entries, 0 to 4835
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                4829 non-null   float64
 1   price_per_area       4829 non-null   float64
 2   land_area            4829 non-null   float64
 3   floor_area           4829 non-null   float64
 4   type                 4829 non-null   object
 5   bedrooms             4829 non-null   object
 6   bathrooms            4829 non-null   int64
 7   address              4829 non-null   object
 8   direction            4829 non-null   object
 9   floor                4829 non-null   object
 10  law_doc              4829 non-null   int64
 11  furniture            4829 non-null   int64
 12  entrance             4829 non-null   object
 13  project              4829 non-null   object
 14  post_date            4829 non-null   object
 15  id                   4829 non-null   object
 16  Ban công             4829 non-null   float64
 17  Sân vườn             4829 non-null   float64
 18  Chỗ đậu xe hơi       4829 non-null   float64
 19  Nuôi thú cưng        4829 non-null   float64
 20  Phòng cho giúp việc  4829 non-null   float64
 21  Phòng giải trí       4829 non-null   float64
 22  Quầy minibar         4829 non-null   float64
 23  Tầng hầm             4829 non-null   float64
 24  Góc làm việc         4829 non-null   float64
 25  Nhà kho              4829 non-null   float64
 26  Gym                  4829 non-null   float64
 27  Hồ bơi riêng         4829 non-null   float64
 28  Giếng trời           4829 non-null   float64
dtypes: float64(17), int64(3), object(9)
memory usage: 1.1+ MB

In [46]:
df['post_date'] = pd.to_datetime(df['post_date'], format='%d/%m/%Y')
df['post_date'] = df['post_date'].astype(str)

In [49]:
df.to_csv("process_nhadat.csv", index= False)

In [50]:
df.to_json("process_nhadat.json", orient='records', lines=True, force_ascii=False)